app = 'terminal-games'
primary_region = 'ord'

# [env]
#   PORT = '23234'

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 22

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'performance-1x'
