# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: "3"

tasks:
  dev:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o ./examples/kitchen-sink/main.wasm ./examples/kitchen-sink
      - GOOS=wasip1 GOARCH=wasm go build -o ./examples/net/main.wasm ./examples/net
      - GOOS=wasip1 GOARCH=wasm go build -o ./cmd/menu/main.wasm ./cmd/menu
      - mold -run cargo run --release -p terminal-games
