version: "3"

tasks:
  example-kitchen-sink:
    dir: examples/kitchen-sink
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o main.wasm .
      - mold -run cargo run --release -- main.wasm
  example-net:
    dir: examples/net
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o main.wasm .
      - mold -run cargo run --release -- main.wasm
