version: "3"

tasks:
  dev:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o ./examples/kitchen-sink/main.wasm ./examples/kitchen-sink
      - GOOS=wasip1 GOARCH=wasm go build -o ./examples/net/main.wasm ./examples/net
      - mold -run cargo run --release
