version: "3"

tasks:
  example-kitchen-sink:
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o ./examples/kitchen-sink/main.wasm ./examples/kitchen-sink
      - mold -run cargo run --release
  example-net:
    dir: examples/net
    cmds:
      - GOOS=wasip1 GOARCH=wasm go build -o main.wasm .
      - mold -run cargo run --release -- main.wasm
