package terminal-games:app@0.1.0;

interface terminal {
    record dimensions {
        width: u16,
        height: u16
    }

    size: func() -> dimensions;
}

world app {
    include wasi:cli/imports@0.2.0;
    export wasi:cli/run@0.2.0;

    import terminal;
}
